version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

    commands:
        # install npm
        - npm install

  build:
    commands:
        # run build script
        - npm run build
        
artifacts:
    files:
        - '**/*'
    base-directory: build
