name: dev

on: 
  push:
    branches:
      - main
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.X

      - run: yarn --frozen-lockfile
      - run: node --experimental-vm-modules node_modules/.bin/jest --config ./jest.config.js --coverage
      - run: npx webpack --config ./webpack.dev.js
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: coverage/**
          retention-days: 5

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/**
          retention-days: 5
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./

      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::520974854908:role/esdb-frontend-dev
          aws-region: ap-northeast-1
      - run: ls | xargs echo 
      - run: cd dist && aws s3 sync . s3://esdb-frontend-dev --exact-timestamps --region ap-northeast-1
